
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongP@ssw0rd!
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P StrongP@ssw0rd! -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 3s

  backend:
    build:
      context: ./Back/BackendTravel
      dockerfile: BackendTravel/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TravelDB;User Id=sa;Password=StrongP@ssw0rd!;TrustServerCertificate=True;
    depends_on:
      sqlserver:
        condition: service_healthy

  frontend:
    build:
      context: ./Front/viajes
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
